apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: apps
data:
  config.yaml: |
    tunnel: vps-cluster-tunnel
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: grafana.carleid.dev
      service: http://monitoring-grafana.monitoring.svc.cluster.local:80
    - hostname: argocd.carleid.dev
      service: https://argocd-server.argocd.svc.cluster.local:443
    - service: http_status:404
