---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAQvml1r6sCAnRCorvHO0J2hbYPKhY40OAOnTUw3gooN40K7WxS3KsL98CpBM+7FEbkJGv/Sto6eDbKBsmx8J8sdOM1J8h0Hcht4czRUD+RABnaUR0j+84aeq6pLh7rv5yKlota0PK7pI2DHMlZt7bbhl3ctp3qkt2VR7zGI+l1K1YDBjFZ56bQjx6jj7QJ1j5g00pL6ONB+YGvb7805ClFD3YOTi0AlzL6n0orIhFgQ3Qsn6roCI996+dwD4Oiq45myyCknIbAFpreheUx1vCk7WeOPNpBabKdjjo3alA3iDKYK2aptNoWEf2Zm+wc/u2+58PK1iD+joMi+z+r08CN2n6M48P0sKW+7AHNW3l89yaA1fqS9zIfeRarzOoI86Bsd8yUYuWsMdtxRMAl0Uyt8lX9nCtfuEzETFrnaWWxBqgUYcILB9/Ckioc/zaln8p45r7JXloh5mQWxLod3eivBOS38EX7EtU5a3o9WefJZy0/5M0rJW5IGnowayicdiAKi14lkhE7QLKpPVs/xO6DPywu7w93nwVh7F4nwSSvcIFJMsku2420WdRHkWizE7i2z/vxv1memY53HiWXmXgkTZO1ePuG8EBiaxmKsnS/NjAGD+nHXwP5UlxaCFzYVd2+iLvx00CpBcWXpf6DW7xvokUL2PFfJYmzRv0VyxYC9IcLYnhsAwDC3QXKMHnL4U1l2+HgE9qbBgU+jgHWQA==
    admin-user: AgBHKR32Dau73UBDiIoETT1kUKOQW2yzZXgwcyC2FT8a9vyj/3d+qM9UmsCEQixyIyfmGcLEMlS8wCBJNw0Rq86gq6ks70dvAsNL0C2W97xwCLMOiWR/LJnHTcKlQ2dMvVUxGUlwSoendLyo2/XrKjbUHd/tK8P19GaHN47yJ060nvi58qh3NmMl5df+M7qRxiOoDu0c6WJ7/Db/0vQu2ZJ1MXszICmzeyit1fVMJOmcKdZ0SSrPqiIgtgDSLAPd280Q72uBK/veN/hIt/QSby3FAta8UIcM+KjLe9oa9zORsv6KPtpajZewSBDddfrYUAxg8ZkJXMuhNu+p1AHwXuzIQuZL/N7UygvdzXhIda25eX2in/xdxGXmxORn51fIfBFf9lheEW2TbEkGp9S1Q9cV6rPjH7UPt+K9eet5jx/rE8EW4AJkpBchz3MzTEiHpIk+Hmy2AsbOw+Xb49OjYBvblSvPYu/Q1UMtjmty2ljAJz2BK/DP1TquLkWu6Un+1WxTI6BeJS1qjzVKUA/RNb54dnXCkfZ9INYJCmyAYMldhffx84N1kBZq8xodtkWqona3YKe6jpKrEv9t13JTi+Vbsw7Ay4BRS7L8dvkniQgQ9BCS1Twk6rEIAD2+m7Fxu5utz2hGsI2RebufwK8VPx9+2ZCTywTJzKLQkuKBNH+wBwsNgQtvdGORamStBUQASLarUTEatQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
