apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homelab-web-secrets
  namespace: homelab-web
spec:
  encryptedData:
    grafana-token: AgCNMDdIrtfQ1gBevqEiuLZ3ElALADOy3MtA1cQJfHLGNfr2LMBVWWi8TIwM4aTH3wUw8136Q6IwmHsHMh9ClDkcPtLWhcOribm7F1qg4NEYhCEbcB8oFX3z8e4dAdi3Ju2h+8FVC5dap5aQPzAgpk/xSQboXely/V0E61hkqLqtDfz110ZkY2ZzlG4b9ISZmD8s8zi8MHcOb6O2Ob1F5OnhDjlEYtHXa46eHHnHyBXOfdgbwid8A10LflpEhnToTWXOKtKwLgXM4kbsPtXhaeQpwKL6r7b5//R3gyt3ffWOY9QV4jG1mlMpUBwGjIFBMfO08gInOGvuEtd+dl2It0SL1IhykVoxgk4iJdQJ4wKjOjTIVHr8k1nzBC+IYl2ZrHUSeeXPbXe4yw6V2Q9lVtSY36EGcL8HXy3u3csRn5BMbGJIGYlagrUMMqOnnfUpIj5b/TJVsvbh7tSXfbbtVDiwEAiOx+EShH2ZTWGJdl9PZ9XQzJ7U7ZcG5L90FuXicoqatw1dJzm1QKfNCWsG8HBvwaorTBC6Sp64U7y1WmlEtT/joase7Wxc4aHSbzJ5N0jVzwONsEZ0XW4ZVjulZtU5EKqjIhXukmo0Hxp4ji5UJXPMo8PUQvEkkljOdChlmM+aNTfGSgSKdBoHaBusux95E32L31g91GyTKxgRgDXD0yQJ0q2OqAyyPJDW6MVhmz7OISlX4GA9AK328HAhgPOnEUVeDK/4sLVj/LojYdCtosY54ftHHYgSrs9OLaa6
  template:
    metadata:
      name: homelab-web-secrets
      namespace: homelab-web
    type: Opaque
