---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: apps
spec:
  encryptedData:
    token: AgBMfNyF3jEyPftuGZemoYObMBkI2AZIszsUCfvfd9kPR9DANT4IiuaTp2+DXltBXrHqhgs5QXFm0/FuIOzeM3yPhcAe+e2EQjZwIjo4BCS4ulzksmIT+wjiZUnbPKHco0kowtWJM7+I4CHZ3AJW4pz4igjRmuIDz4OgYdhqMJHkY14s98FP9sb3YNgwL7Gv3uOmvLZfMA2XBIk3Juke1iq5wMdqxO5uvHM3Q/kLtLQxWTutf2ikLCSYjT477rWxaZXx0NASqVTDZr4BzZPR0AZkta20FlA8H8zYzbuRPPhYxSuc15+yPAy2juVrEW2ewgrK5yYgYC3Dl57cskGdFGI9R0HZEu0JIMeYgXn//21KETH5o8tbS6s6n7cHGPP9iipFeJ/GIRU/uQ2lrTwELM9Ouyg2lLMViYezrI4n1d3z0MEs9oLrEI7Lr0TzzA6cBuMyhl6ipowFWs8CoAYhV5XjRbWkK2eEEIjP4kdtDxEjvW1wOTG/zUL14leIaqNBDXBW51nBBdShQa9zT3HJAWJj6Q4DPUFiDxyho1PnchjJIMXmW4X5BEBdGBhS6tXueuJnPaX0ulOUg8hdv+ps4PUbMEKzqZgl0f3Cw1EfnG9FP34SygK9v0Mn0qD5tQh3Uj6K6tERfR8ZTkZVVZieh27vDNSwr9FCHMELN1kSDHLzbw0HFXmY9MzZg7MIUmIv1sJDCzc9SHPlxZB7y1y3NjL/45i5jHDyFU19sK6EPmVllgYr/VfCBK7yYdplZILlAbGmpf4QhHY5c7qH6OSApOz5MgZwFy2l624vLNYpxyo0quS5WyOR0Q4O2BHAHYIXSEHq6t7SplevgzMk5QmNbsxIq1d6N2gwUm/CsegYcwU46yIsf7CwdeKDJTTr35zFeTXOTKZgXoQ1CZESa0gQf3gl4WUhbJM0wBGwsGLbtUzFa6Zn0ko=
  template:
    metadata:
      name: cloudflared-credentials
      namespace: apps
