apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/carleid-homelab/homelab.git
    targetRevision: HEAD
    path: k8s/platform/argocd-metrics
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
